### ISSUE TITLE
Install Code Review Doctor 

### ISSUE THREAD

**Issue by ikhoon** [line/centraldogma-python#28]
I think we can use [Code Review Doctor](https://codereview.doctor/) to check common mistakes automatically.
https://codereviewdoctor.medium.com/5-of-666-python-repos-had-comma-typos-including-tensorflow-and-pytorch-sentry-and-v8-7bc3ad9a1bb7

**Comment by hexoul** [comment]
Good to know! Would it be better to add to README and MR? BTW, we have 9 issues https://codereview.doctor/line/centraldogma-python

**Comment by code-review-doctor** [comment]
:wave: you can add me via [GitHub marketplace(https://github.com/marketplace/django-doctor/) so your PRs are checked for the issues I look out for :)

**Comment by hexoul** [comment]
@ikhoon @minwoox @syleeeee 
It costs $49 per a month for organizations. 😅 As LINE have [a few of repositories](https://github.com/orgs/line/repositories?q=&type=all&language=python) written in Python, adopting it could be useful if the organization don't mind to pay. However, if not, I want to close this issue. Please tell their opinions.

**Comment by ikhoon** [comment]
A small number of pull requests are made in this repo, so I don't think we really need it.

**Comment by hexoul** [comment]
> A small number of pull requests are made in this repo

p.s. That I said "As LINE have a few of repositories written in Python" is about their pricing. $49 up to 10 repositories.
