### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by yu74n** [line/centraldogma-python#30]
Installing this client with `pip install` is very useful.
Is there any obstacle to publish this client to PyPI?

**Comment by hexoul** [comment]
Thanks for your interesting! Sure. This is in progress though, I also would like to publish.
To progress, we need to discuss about account for author represented at PyPi and so on. @ikhoon @minwoox

**Comment by ikhoon** [comment]
We haven't proceeded with this project for a while because of busy days.
I am eager to take the time to release an early version soon.
Let's have a chat to summarize the remaining tasks and schedule when we can release this.

**Comment by hexoul** [comment]
Now we are ready! When creating a release, it will be published. https://github.com/line/centraldogma-python/releases/new

@syleeeee How about trying? cc. @ikhoon @minwoox

**Comment by ikhoon** [comment]
Finally, 0.1.1 has been released. https://github.com/line/centraldogma-python/releases/tag/0.1.1 😄
