### ISSUE TITLE
Publish Sphinx documentation for users

### ISSUE THREAD

**Issue by hexoul** [line/centraldogma-python#33]
to Github page maybe. If there is other option, we can discuss.

**Comment by ikhoon** [comment]
If Sphinx documentation is not only a good reference and but also a good tutorial, we may ignore #32, and add a link to the documentation should be enough.

**Comment by hexoul** [comment]
I think we are able to utilize Sphinx for a good tutorial, but no need to ignore #32. This is because README is landing page of our PyPi project so users can break away from documentation pages if README seems low quality.
