### ISSUE TITLE
update README and documentation to use http2

### ISSUE THREAD

**Issue by darjeeling** [line/centraldogma-python#39]
I installed package and used example code from README.md.

but I got import error, as I read the code it's default value. so I think it should be documented well

```
ImportError: Using http2=True, but the 'h2' package is not installed. Make sure to install httpx using `pip install httpx[http2]`.
```

I think we need to update this on README.md and documentation

**Comment by hexoul** [comment]
Sorry for this inconvenience.
No need to update README. Instead, `setup.py` needs to be updated. As a default configuration of this package uses http2, `http2` extra package is required now. Before updating, please install like below
```sh
$ pip install httpx[http2]
$ pip install centraldogma-python
```
