### ISSUE TITLE
User 'centraldogma_line' does not have a verified primary email address

### ISSUE THREAD

**Issue by hexoul** [line/centraldogma-python#51]
https://github.com/line/centraldogma-python/actions/runs/11347459048/job/31558889376

```
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
         User 'centraldogma_line' does not have a verified primary email        
         address. Please add a verified primary email before attempting to      
         upload to PyPI. See https://pypi.org/help/#verified-email for more     
         information. 
```

Please check PyPI account status 🙏 @darjeeling or someone else.

**Comment by hexoul** [comment]
@jrhee17 @ikhoon @minwoox PTAL🙏 I cannot handle this issue because  it is about LINE account problem.

**Comment by jrhee17** [comment]
Thanks for pinging us, let me check right now 🙏

**Comment by jrhee17** [comment]
Sorry about the delay, @syleeeee is checking at the moment

**Comment by ikhoon** [comment]
I think it's time to return to LY (ex. LINE). 😆

**Comment by jrhee17** [comment]
https://github.com/line/centraldogma-python/actions/runs/11347459048/job/31921142935#step:5:211

It seems like 2FA also needs to be enabled

**Comment by jrhee17** [comment]
Upload has succeeded: https://github.com/line/centraldogma-python/actions/runs/11347459048/job/31921315295

**Comment by hexoul** [comment]
Thanks! I also checked https://pypi.org/project/centraldogma-python
